Repository arcus-azure/arcus.scripting, pull requests merged in 2025-02, with the labels that each got.

#447 docs: Move and improve Devops documentation
  docs/preview/02-Guidelines/setting-arm-outputs-to-azure-devops-variable-group.md
  docs/preview/03-Features/powershell/azure-devops.md
Labels: documentation, area:devops

#453 docs: publish v1.5.0 feature docs
  docs/versioned_docs/version-v1.5.0/01-index.md
  docs/versioned_docs/version-v1.5.0/02-Guidelines/Installation.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-active-directory.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-api-management.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-app-service.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-data-factory.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-devops.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-integration-account.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-key-vault.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-logic-apps-consumption.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-logic-apps-standard.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-management.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-security.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-sql.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-storage/_category_.yml
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-storage/azure-storage-all.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-storage/azure-storage-blob.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-storage/azure-storage-fileshare.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-storage/azure-storage-table.md
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/templates/_category_.yml
  docs/versioned_docs/version-v1.5.0/03-Features/powershell/templates/arm.md
  docs/versioned_sidebars/version-v1.5.0-sidebars.json
  docs/versions.json
Labels: documentation

#456 chore(docs): auto-trigger new feature docs version via release pipeline
  .github/workflows/bump-docs-version.yml
  build/psgallery-release.yml
  build/templates/trigger-bump-docs-version.yml
Labels: documentation, enhancement, management
